config/routes.rb
CTABuses::Application.routes.draw do

  root to: "bus_stops#index"

  get 'bus_stops/stopcounts' => 'bus_stops#stopcounts'

  get 'bus_stops/routecounts' => 'bus_stops#stopcounts'
  resources :bus_stops, only: [:show, :index]
  resources :bus_routes, only: [:show, :index]

end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  has_many :stop_on_routes, foreign_key: "stop_id",
                             primary_key: "stop_id" 

  def self.get_route_detail
    select("*").joins(:stop_on_routes)
  end

  def self.get_stop_counts
    get_route_detail.select("*,count(route) as count")
                    .group("bus_stops.stop_id")
                    .order("count desc")

  end
end





# BusStop 

# stop_id:integer
# cross_street:string
# boardings: float
# alightings:float
# month_beginning: string
# daytype:string 
# loc_lat:float
# loc_long:float

app/models/stop_on_route.rb
class StopOnRoute < ActiveRecord::Base
  has_many :bus_stops, foreign_key: "stop_id",
                       primary_key: "stop_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bus_routes_controller.rb
class BusRoutesController < ApplicationController
  def show
    @bus_stops = all_stops(params[:id])
    @bus_stops_paginated = @bus_stops.paginate(page: params[:page],
                                               per_page: 10)
                                    
    @boardings = total_boardings @bus_stops
    @alightings = total_alightings @bus_stops
    @street = get_representative_street params[:id]



   
  end

  def index
    @routes = StopOnRoute.select("COUNT(stop_id) as num_stops, route")
                          .group("route").order("num_stops desc")
                          .paginate(page: params[:page])

    # the number of stops that represent 50% of the total boardings
    # divided by number of stops on the route


  end

  private 

    def all_stops(route_id)
      BusStop.get_route_detail
             .where("stop_on_routes.route = ?",route_id)
             .order("boardings desc")
    end

    def total_boardings(stops)
      stops.sum('boardings')
    end

    def total_alightings(stops)
      stops.sum('alightings')
    end

    def get_representative_street(route_id)
      all_stops(route_id).select("count(on_street) as count,on_street")
                         .group("on_street").order("count desc")
                         .limit(1).first.on_street.titlecase
    end
end

app/controllers/bus_stops_controller.rb
class BusStopsController < ApplicationController
  def index
    @bus_stops = BusStop.all.paginate(page: params[:page])

  end

  def show
    @stop = BusStop.find_by(stop_id: params[:id])
    @routes = StopOnRoute.where('stop_id = ?', params[:id])
  end

  def stopcounts
      @bus_stops = BusStop.get_stop_counts                  
                          .paginate(page: params[:page])                  

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_routes_helper.rb
module BusRoutesHelper
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/views/bus_routes/index.html.erb
<h1>All Routes</h1>

<%= will_paginate @routes %>

<table class="table table-striped">
  <tr>
    <th>Route</th>
    <th>Number of Stops</th>
  </tr>
  <% @routes.each do |r| %>
    <tr>
      <% unless r.route.nil? %>
        <td><%= link_to "#{r.route}", bus_route_path(r.route) %></td>
      <% end %>
      <td><%=r.num_stops %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @routes %>

app/views/bus_routes/show.html.erb
<h1>Route <%= params[:id] %></h1>

<h3><em><%=@street%></em></h3>

<h3>Stats:</h3>
<dl class="dl-horizontal">
  <dt>Total Boardings:</dt> <dd><%= @boardings.floor %> </dd>
  <dt>Total Alightings:</dt> <dd><%= @alightings.floor %></dd>
</dl>


<h3>Stops (<%= @bus_stops.length %>):</h3>


<table class="table table-striped"/>

  <tr>
    <th>Stop ID</th>
    <th>On Street</th>
    <th>Cross Street</th>
    <th>Boardings</th>
    <th>Alightings</th>
    <th>Location</th>
  </tr>

  <% @bus_stops_paginated.each do |stop| %>

    <tr>
      <td><%= link_to "#{stop.stop_id}", bus_stop_path(stop.stop_id) %></td>
      <td><%= stop.on_street %></td>
      <td><%= stop.cross_street %></td>
      <td><%= stop.boardings %></td>
      <td><%= stop.alightings %></td>
      <td>(<%=stop.loc_lat%>, <%=stop.loc_long%>)</td>
    </tr>

  <% end %>

</table>

<%= will_paginate @bus_stops_paginated %>

app/views/bus_stops/index.html.erb
<h1>All Bus Stops</h1>

<h4>
   <%= link_to "View stops on most routes", bus_stops_stopcounts_path %>  
</h4>



<%= will_paginate @bus_stops %>

<table class="table table-striped"/>

  <tr>
    <th>Stop ID</th>
    <th>On Street</th>
    <th>Cross Street</th>
    <th>Boardings</th>
    <th>Alightings</th>
    <th>Location</th>
  </tr>

  <% @bus_stops.each do |stop| %>

    <tr>
      <td><%= link_to "#{stop.stop_id}", bus_stop_path(stop.stop_id) %></td>
      <td><%= stop.on_street %></td>
      <td><%= stop.cross_street %></td>
      <td><%= stop.boardings %></td>
      <td><%= stop.alightings %></td>
      <td>(<%=stop.loc_lat%>, <%=stop.loc_long%>)</td>
    </tr>

  <% end %>



</table>









<%= will_paginate @bus_stops %>

app/views/bus_stops/show.html.erb
  <h1>Bus Stop <%= @stop.stop_id %></h1> 

  <h3><em>
    <%= @stop.on_street.titlecase %> and 
    <%= @stop.cross_street.titlecase %>
  </em></h3>

  <h3>Stats:</h3>
  <dl class="dl-horizontal">
    <dt>Boardings</dt> <dd><%= @stop.boardings %></dd>
    <dt>Alightings:</dt> <dd><%= @stop.alightings %></dd>  
  </dl>

  <h4>On <%= pluralize(@routes.length,"Route") %>:</h4>
    |
    <% @routes.each do |r| %>
      <%= link_to "#{r.route}", bus_route_path(r.route) %> |
    <% end %>

    <h3>Map</h3>

    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map-canvas { height: 700px; 
                    width: 700px;
                  }
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?&sensor=false">
    </script>
    <script type="text/javascript">
      function initialize() {
        var stopLatLng = new google.maps.LatLng(<%= "#{@stop.loc_lat}, #{@stop.loc_long}" %>);
        var mapOptions = {
          center: stopLatLng,
          zoom: 16 
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
        var stopMarker = new google.maps.Marker({
          position: stopLatLng,
          map: map,
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

    <div id="map-canvas"/>

app/views/bus_stops/stopcounts.html.erb
<h1>All Stops (ordered by routes)</h1>

<%= will_paginate @bus_stops %>


<table class="table table-striped"/>

  <tr>
    <th>Stop ID</th>
    <th># of Routes</th>
    <th>On Street</th>
    <th>Cross Street</th>
    <th>Boardings</th>
    <th>Alightings</th>
    <th>Location</th>
  </tr>

  <% @bus_stops.each do |stop| %>

    <tr>
      <td><%= link_to "#{stop.stop_id}", bus_stop_path(stop.stop_id) %></td>
      <td><%= stop.count %></td>
      <td><%= stop.on_street %></td>
      <td><%= stop.cross_street %></td>
      <td><%= stop.boardings %></td>
      <td><%= stop.alightings %></td>
      <td>(<%=stop.loc_lat%>, <%=stop.loc_long%>)</td>
    </tr>

  <% end %>
</table>

<%= will_paginate @bus_stops%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CTABuses</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

      <%= link_to "Routes", bus_routes_path %> |
      <%= link_to "Stops", bus_stops_path %>


  </div>

<%= yield %>

</body>
</html>